// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunGame(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['RunGame'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function RunServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunServer'](arg1, arg2, arg3);
}

export function SelectClientPath() {
  return window['go']['main']['App']['SelectClientPath']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
