// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunGame(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function RunServer(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SelectClientPath():Promise<string>;

export function StopServer():Promise<void>;
